export const UserRole = Object.freeze({
  VOTER: 'VOTER',
  CANDIDATE: 'CANDIDATE',
  EXECUTIVE: 'EXECUTIVE',
  SUPERVISOR: 'SUPERVISOR',
  USER: 'USER',
  ADMIN: 'ADMIN'
})
 export const RequestStatus = Object.freeze({
  DRAFT: 'DRAFT',  
  CANDIDATE: 'CANDIDATE',
  CONDITIONS_ACCEPTED: 'CONDITIONS_ACCEPTED',
  DOCUMENTS_UPLOADED: 'DOCUMENTS_UPLOADED',
SUBMITTED: 'SUBMITTED',
  EXECUTIVE_APPROVED: 'EXECUTIVE_APPROVED',
  EXECUTIVE_REJECTED: 'EXECUTIVE_REJECTED',

  SUPERVISION_APPROVED: 'SUPERVISION_APPROVED',
  SUPERVISION_REJECTED: 'SUPERVISION_REJECTED',

  OBJECTION_SUBMITTED: 'OBJECTION_SUBMITTED'
})
